### ISSUE TITLE
Is it possible to use `bunch` to track itself as a dependency?

### ISSUE THREAD

**Issue by tamird** [dkulchenko/bunch#17]
I'd like to use a pinned version of `bunch` itself, but not sure if this is currently possible, or even theoretically possible given the bootstrapping problem. cc @bdarnell

**Comment by dkulchenko** [comment]
Not sure how this would work. I'd recommend using the tagged precompiled release builds (or building from a vendored git clone) in production. I used bunch to build bunch at one point, but you end up with the scenario where if the build of bunch fails, you're out the package manager you're using to build itself - the cycle breaks.

**Comment by bdarnell** [comment]
With [glock](https://github.com/robfig/glock), bootstrapping works because it just installs itself into `$GOPATH/bin`, which is already on your `$PATH`. It's true that if the installation corrupts that binary then you're out of luck but it shouldn't overwrite the file until the build has completed. For `bunch`, since it doesn't manage files in `$GOPATH/bin`, it's a little trickier. One solution would be for `main()` to look for `.vendor/bin/bunch`, and exec it if it exists. This way you've have a bootstrapping version of `bunch` in `$GOPATH` but in most cases it would pass through to the inner `.vendor` version.

**Comment by dkulchenko** [comment]
@bdarnell, I like that idea, thanks! Implemented in 8f02eb9.

**Comment by dkulchenko** [comment]
Reopening, this created a new bug.

**Comment by dkulchenko** [comment]
Fixed in d21e0b05.

**Comment by tamird** [comment]
Please reopen this - when the versions don't match, `bunch` spirals into infinite recursion.

**Comment by dkulchenko** [comment]
Are you running w/the latest commit 427b9aa? It should address that situation, may need a "go get -u" to update globally and wiping/reinstalling the vendored one as well.

**Comment by tamird** [comment]
Yeah, that's what happened. Perhaps we should have a fallback so that if running the vendored bunch fails we still run the global one?

**Comment by dkulchenko** [comment]
Can do, but the question is then - did the vendored bunch fail because it's broken or did it fail because bunch didn't succeed for some other reason (e.g. the Bunchfile specified deps are wrong). If it's the latter, we'd run through the bunch steps twice for no reason and end up with the error doubled.

**Comment by tamird** [comment]
I think that situation is preferred to the situation in which bunch is broken and `bunch update github.com/dkulchenko/bunch` can't fix it

**Comment by dkulchenko** [comment]
Agreed, done in 85e3a193.
